### ISSUE TITLE
About Light Sources

### ISSUE THREAD

**Issue by mono0218** [noname0310/babylon-mmd#16] opened 2024-01-10 12:47 UTC
I imported a PMX MMD stage and the colors look a little pale.
 I tried changing the light code to look like the official page, but it didn't cure it. 
On [this]( https://noname0310.github.io/babylon-mmd/pmx_converter/) page the colors appear as normal. Is there something wrong with the light code?

**Comment by noname0310** [comment] 2024-01-10 14:22
This appears to happen when the diffuse color of the model's material is not (1, 1, 1).

Some MMD models use the approach of setting the diffuse color to (0.5, 0.5, 0.5) and the ambient color to (1, 1, 1) to create a material that looks bright in the dark.

However, if we simply import the deffuse and ambient parameters into the StandardMaterial in babylon.js, we will get different lighting results due to the different way ambient color works in babylon.js.

In simple terms, this is due to the different behavior of babylon.js and MMD materials,
and can be resolved by applying either of the two codes below.

option1:
```typescript
const pmxLoader = SceneLoader.GetPluginForExtension(".pmx") as PmxLoader;
const pmxMaterialBuilder = pmxLoader.materialBuilder as MmdStandardMaterialBuilder;
pmxMaterialBuilder.afterBuildSingleMaterial = (material): void => {
    material.diffuseColor.add(material.ambientColor);
    material.ambientColor.set(0, 0, 0);
};
````

option2:
```typescript
scene.ambientColor = new Color3(1, 1, 1);
```

The second option is theoretically similar to MMD, although the first option usually yields better results

If you have any other questions, feel free to open an issue and I'll get back to you shortly.

**Comment by noname0310** [comment] 2024-01-10 15:57
If you're using post-processing, tone mapping may be the cause
```typescript
defaultPipeline.imageProcessing.toneMappingEnabled = false;
```

**Comment by noname0310** [comment] 2024-05-10 03:55
In 0.41.0, the renderer code was refactored across the board, and you should now see exactly the same results as MMD.

**Closed** 2024-12-22 02:20 UTC
Labels: question
